### ISSUE TITLE
Add basic parse transform

### ISSUE THREAD

**Issue by greatislander** [fluid-project/eleventy-plugin-fluid#21]
## Is your feature request related to a problem?

We include a default [parse transform](https://github.com/fluid-project/fluidic-11ty/blob/main/src/transforms/parse-transform.js) which enables native lazy-loading of images in the main content area.

## Describe the solution you'd like

This parse transform should be included in the plugin.

## Describe alternative solutions you've considered

Not applicable.

## Additional context or notes

Not applicable.

**Comment by Akshat162001** [comment]
function parseTransform(code) {
  // Perform your parse transformation logic here
  // Modify the code or manipulate the abstract syntax tree (AST) if needed
  
  // For this example, let's simply append a console.log statement to the code
  const transformedCode = code + "\nconsole.log('Transformation applied');";
  
  return transformedCode;
}

// Example usage
const originalCode = `
function greet(name) {
  return 'Hello, ' + name + '!';
}
`;

const transformedCode = parseTransform(originalCode);
console.log(transformedCode); u mean to say this parse??

**Comment by greatislander** [comment]
This seems better left to individual implementations.
