### ISSUE TITLE
Add multilingual UIO

### ISSUE THREAD

**Issue by greatislander** [fluid-project/eleventy-plugin-fluid#58]
## Is your feature request related to a problem?

The new multilingual UIO support added in https://github.com/fluid-project/trivet/pull/148 should be moved here.

## Describe the solution you'd like

Ability for UIO initialization shortcode to accept a language code and direction (`ltr` or `rtl`) and initialize UIO in that language.

## Describe alternative solutions you've considered

Not applicable.

## Additional context or notes

UIO needs to fall back to the default locale if a requested locale is not available.

**Comment by jobara** [comment]
The Infusion 4.0.0-dev.20210622T193827Z.ac6adb829.FLUID-6629 adds additional multilingual support for UIO. 

See: https://unpkg.com/browse/infusion@4.0.0-dev.20210622T193827Z.ac6adb829.FLUID-6629/src/components/uiOptions/js/UIOptions.js
