### ISSUE TITLE
figure shortcode injects `<br>` for line breaks.

### ISSUE THREAD

**Issue by jobara** [fluid-project/eleventy-plugin-fluid#76]
## Describe the bug

The figure shortcode is configured to inject `<br>` tags when it encounters a line break in the fig caption. The issue is that we may want to use line breaks to enforce readability of the raw Markdown file in source, but not want those included in the rendered HTML.

It appears this is due to [configuration](https://github.com/fluid-project/eleventy-plugin-fluid/blob/d7904d9d3f1b579c0c1a6df0b32e9e77d3abdb3d/src/shortcodes/figure-shortcode.js#L28) set on the Markdown-in markdown renderer.

see: [Markdown-It options](https://github.com/markdown-it/markdown-it#init-with-presets-and-options)

### Expected behavior

The expectation is that the line breaks within paragraphs in Markdown files are ignored, not injecting `<br>` tags.

**Comment by greatislander** [comment]
You'll want to address this too: https://github.com/fluid-project/eleventy-plugin-fluid/blob/main/src/filters/markdown-filter.js#L19
