### ISSUE TITLE
Pre-Release peerDependencies break in NPM 7+

### ISSUE THREAD

**Issue by jobara** [fluid-project/eleventy-plugin-fluid#86]
## Describe the bug

This plugin includes a [peerDependency on Infusion 4.x](https://github.com/fluid-project/eleventy-plugin-fluid/blob/467eafc6b49370f4b0af5037f9bf54285b9386db/package.json#L51-L53). However, Infusion 4 has not had a stable release and has only published dev releases. NPM 7 and higher will automatically try to install peerDependencies; however, it throws the following error.

```log
ERESOLVE overriding peer dependency
npm WARN While resolving: eleventy-plugin-fluid@0.3.1
npm WARN Found: infusion@undefined
npm WARN node_modules/infusion
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer infusion@"4.x" from eleventy-plugin-fluid@0.3.1
npm WARN node_modules/eleventy-plugin-fluid
npm WARN   eleventy-plugin-fluid@"0.3.1" from the root project
npm ERR! code ETARGET
npm ERR! notarget No matching version found for infusion@4.x.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

see: https://github.com/npm/cli/issues/2087

### To reproduce
1. Ensure you're running NPM 7 or higher
2. run `npm install eleventy-plugin-fluid` to install the package
3. Notice the error mentioned above

### Expected behavior

The package installs correctly.

## Additional context or notes

[Peer Dependencies](https://nodejs.org/es/blog/npm/peer-dependencies/)

**Comment by amb26** [comment]
What should we do?

**Comment by jobara** [comment]
If the `--legacy-peer-deps` flag is used when running `npm install`, it will install without errors.

**Comment by jobara** [comment]
@amb26 the simplest fix would probably to not include a peerDependency section in the package.json, and just document which version of Infusion is required and ask the user to install that manually. 

I wonder if we could also try to target a pre-release or higher for the peer dependency. Something like `>=4.0.0-dev.0`. If the problem is just that it assumes that `4.x` is a stable release and ignores all pre-releases.

**Comment by greatislander** [comment]
Since we now have a stable Infusion 4.0 release I think this can be closed.
